### ISSUE TITLE
Source data is located in a local directory

### ISSUE THREAD

**Issue by otravers** [mohaali/PowerBIExamples#1]
The bike sharing data source is currently:
C:\Users\muali\Desktop\bike_sharing_daily.csv

Ideally instead you can put that file in a public cloud location (e.g. Github too), so that the whole solution (including Power Query) works.

**Comment by mohaali** [comment]
Thanks for the comment, ill share the dataset now

**Comment by mohaali** [comment]
Added - let me know if that works for you

**Comment by otravers** [comment]
Yes, that was fast! Just so it's seamless for other people, you might want to edit the Source step at the beginning of your PQ code to:

= Csv.Document(Web.Contents("https://raw.githubusercontent.com/mohaali/PowerBIExamples/master/Python%20blog%20post%201%20-%20A%20new%20hope/bike_sharing_daily.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None])

**Comment by mohaali** [comment]
Fixed that problem too - let me know if it works now for you

**Comment by mohaali** [comment]
and thanks for the suggestion
